<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Cloud, FolderOpen, LogOut, Plus, RefreshCw, Shield, Trash2, Pencil } from 'lucide-vue-next'
type Job={id:string;name:string;enabled:boolean;source_dir:string;output_dir:string;extensions:string[];delete_missing:boolean;scan_mode:string;schedule:string;base_url:string}
type Item={name:string;path:string;directory:boolean;size:number}
const logged=ref(false),busy=ref(false),error=ref(''),notice=ref(''),token=ref('')
const settings=ref({address:'',token:'',token_masked:''}),jobs=ref<Job[]>([]),browsePath=ref('/'),items=ref<Item[]>([]),showPicker=ref(false)
const form=ref<Job>({id:'',name:'',enabled:true,source_dir:'/',output_dir:'',extensions:['.mkv','.mp4','.avi'],delete_missing:false,scan_mode:'manual',schedule:'',base_url:window.location.origin})
const extensions=ref('.mkv, .mp4, .avi')
const editingId=ref('')
function editJob(job:Job){editingId.value=job.id;form.value={...job,extensions:[...job.extensions]};extensions.value=job.extensions.join(', ');window.scrollTo({top:0,behavior:'smooth'})}
function cancelEdit(){editingId.value='';form.value={id:'',name:'',enabled:true,source_dir:'/',output_dir:'',extensions:['.mkv','.mp4','.avi'],delete_missing:false,scan_mode:'manual',schedule:'',base_url:window.location.origin};extensions.value='.mkv, .mp4, .avi'}
async function request<T>(url:string,method='GET',body?:unknown):Promise<T>{const response=await fetch(url,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data as T}
async function run(fn:()=>Promise<void>){busy.value=true;error.value='';notice.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function refresh(){settings.value={...(await request<{address:string;token_masked:string}>('/api/settings')),token:''};jobs.value=await request<Job[]>('/api/jobs')}
async function login(){await run(async()=>{await request('/api/login','POST',{token:token.value});token.value='';logged.value=true;await refresh()})}
async function logout(){await run(async()=>{await request('/api/logout','POST');logged.value=false})}
async function saveSettings(){await run(async()=>{await request('/api/settings','PUT',{address:settings.value.address,token:settings.value.token});settings.value.token='';await refresh();notice.value='CloudDrive2 连接和令牌已验证'})}
async function loadDir(path:string){await run(async()=>{items.value=await request<Item[]>('/api/browse?path='+encodeURIComponent(path));browsePath.value=path;showPicker.value=true})}
async function saveJob(){await run(async()=>{form.value.extensions=extensions.value.split(',').map(x=>x.trim()).filter(Boolean);const job=await request<Job>(editingId.value?`/api/jobs/${editingId.value}`:'/api/jobs',editingId.value?'PUT':'POST',form.value);if(editingId.value){jobs.value=jobs.value.map(x=>x.id===job.id?job:x);notice.value='任务已更新'}else{jobs.value.unshift(job);notice.value='任务已创建'}cancelEdit()})}
async function scan(j:Job){await run(async()=>{const x=await request<{files_seen:number;files_written:number}>(`/api/jobs/${j.id}/scan`,'POST');notice.value=`${j.name} 扫描完成：${x.files_seen} 个媒体文件，写入 ${x.files_written} 个 STRM`})}
async function remove(j:Job){if(!window.confirm(`删除任务“${j.name}”及其生成的 STRM 文件？`))return;await run(async()=>{await request(`/api/jobs/${j.id}`,'DELETE');jobs.value=jobs.value.filter(x=>x.id!==j.id);notice.value='任务已删除'})}
async function rotate(){const current=window.prompt('输入当前 Admin Token 以轮换');if(!current)return;await run(async()=>{const result=await request<{token:string}>('/api/admin/rotate','POST',{current});logged.value=false;window.alert('新 Admin Token（仅显示一次，请立即保存）：\n'+result.token)})}
onMounted(async()=>{try{await request('/api/me');logged.value=true;await refresh()}catch{logged.value=false}})
</script>
<template>
 <div class="shell"><header class="row"><Cloud :size="28" color="#69d7bf"/><div><strong>CD2 STRM Gateway</strong><small>CloudDrive2 直链网关</small></div><div class="spacer"/><button v-if="logged" class="btn" @click="logout"><LogOut :size="16"/> 退出</button></header>
 <main v-if="!logged" class="login card"><Shield :size="36" color="#69d7bf"/><h1>管理员登录</h1><p class="muted">输入首次启动日志中的 Admin Token</p><form @submit.prevent="login"><div class="field"><label>Admin Token</label><input v-model="token" type="password" autocomplete="off" required/></div><button class="btn primary" :disabled="busy">登录</button></form></main>
 <main v-else class="content"><div class="row intro"><div><h1>管理控制台</h1><p class="muted">浏览云端媒体，生成稳定 STRM，播放时获取直链。</p></div><div class="spacer"/><button class="btn" @click="rotate">轮换 Admin Token</button></div>
 <div v-if="error" class="banner error">{{ error }}</div><div v-if="notice" class="banner success">{{ notice }}</div>
 <div class="grid panels"><section class="card"><h2><Cloud :size="19"/> CloudDrive2 连接</h2><form @submit.prevent="saveSettings"><div class="field"><label>gRPC 地址</label><input v-model="settings.address" placeholder="http://192.168.1.x:19798" required/><small>填写 CloudDrive2 主机的直连地址；普通网页反向代理通常不能转发原生 gRPC。</small></div><div class="field"><label>API Token <span class="muted">{{settings.token_masked ? `当前：${settings.token_masked}；留空则保持` : ''}}</span></label><input v-model="settings.token" type="password" autocomplete="new-password" placeholder="粘贴 CloudDrive2 API Token"/></div><button class="btn primary" :disabled="busy">验证并保存</button></form></section>
 <section class="card"><h2><Plus :size="19"/> {{editingId?'编辑':'新建'}} STRM 任务</h2><form @submit.prevent="saveJob"><div class="grid two"><div class="field"><label>名称</label><input v-model="form.name" required/></div><div class="field"><label>源目录</label><div class="row"><input v-model="form.source_dir" :disabled="!!editingId" required/><button type="button" class="btn" :disabled="!!editingId" @click="loadDir(form.source_dir)"><FolderOpen :size="16"/></button></div></div></div><div class="field"><label>本地输出目录（绝对路径）</label><input v-model="form.output_dir" :disabled="!!editingId" placeholder="/strm/media" required/></div><div class="field"><label>网关公开地址</label><input v-model="form.base_url" :disabled="!!editingId" required/></div><div class="field"><label>媒体扩展名（逗号分隔）</label><input v-model="extensions"/></div><div class="row"><label><input v-model="form.enabled" type="checkbox"/> 启用任务</label><label><input v-model="form.delete_missing" type="checkbox"/> 删除源端已不存在的 STRM</label><div class="spacer"/><button v-if="editingId" type="button" class="btn" @click="cancelEdit">取消</button><button class="btn primary" :disabled="busy">{{editingId?'保存修改':'创建任务'}}</button></div></form></section></div>
 <section class="card jobs"><h2>STRM 任务</h2><p v-if="!jobs.length" class="muted">还没有任务。配置 CloudDrive2 后创建第一个任务。</p><div v-for="j in jobs" :key="j.id" class="job row"><div><strong>{{j.name}}</strong><div class="muted detail">{{j.source_dir}} → {{j.output_dir}}</div><small>{{j.enabled?'已启用':'已停用'}} · {{j.extensions.join(', ')}} · {{j.delete_missing?'同步删除':'保留旧文件'}}</small></div><div class="spacer"/><button class="btn" :disabled="busy||!j.enabled" @click="scan(j)"><RefreshCw :size="16"/> 扫描</button><button class="btn" :disabled="busy" @click="editJob(j)"><Pencil :size="16"/> 编辑</button><button class="btn danger" :disabled="busy" @click="remove(j)"><Trash2 :size="16"/></button></div></section>
 </main>
 <div v-if="showPicker" class="overlay" @click.self="showPicker=false"><div class="card picker"><div class="row"><h2>选择 CloudDrive2 目录</h2><div class="spacer"/><button class="btn" @click="showPicker=false">关闭</button></div><p class="muted">{{browsePath}}</p><button v-if="browsePath!=='/'" class="dir" @click="loadDir(browsePath.slice(0,browsePath.lastIndexOf('/'))||'/')">.. 返回上级</button><button v-for="item in items.filter(x=>x.directory)" :key="item.path" class="dir" @click="loadDir(item.path)"><FolderOpen :size="16"/> {{item.name}}</button><button class="btn primary" @click="form.source_dir=browsePath;showPicker=false">选择此目录</button></div></div>
 </div>
</template>
<style scoped>.shell{min-height:100vh}header{height:70px;border-bottom:1px solid #263a4d;padding:0 max(24px,calc((100vw - 1200px)/2));background:#111d2b}header strong{display:block;font-size:17px}header small{display:block}.content{max-width:1200px;padding:38px 24px;margin:auto}.intro{margin-bottom:24px}.intro p{margin:0}.panels{grid-template-columns:1fr 1.4fr}.two{grid-template-columns:1fr 1fr}.card h2{display:flex;gap:9px;align-items:center}.login{max-width:420px;margin:12vh auto}.banner{padding:12px 16px;border-radius:8px;margin-bottom:18px;background:#203247}.jobs{margin-top:18px}.job{border-top:1px solid #2a4053;padding:18px 0}.detail{font-size:13px;margin:5px 0;overflow-wrap:anywhere}.overlay{position:fixed;inset:0;background:#07101acb;display:grid;place-items:center;padding:20px}.picker{width:min(540px,100%);max-height:80vh;overflow:auto}.dir{display:flex;gap:10px;width:100%;padding:10px;background:transparent;color:#dce7f1;border:0;text-align:left;border-radius:7px}.dir:hover{background:#21364a}label input[type=checkbox]{width:auto;margin-right:6px}.btn svg{vertical-align:middle}@media(max-width:800px){.panels,.two{grid-template-columns:1fr}.content{padding:24px 14px}.intro{align-items:flex-start}}</style>
